import type { ComplianceDashboardData } from '@/types/compliance';

// Helper to get dates relative to today
const addDays = (days: number): string => {
  const date = new Date();
  date.setDate(date.getDate() + days);
  return date.toISOString();
};

const addHours = (hours: number): string => {
  const date = new Date();
  date.setHours(date.getHours() + hours);
  return date.toISOString();
};

export const mockComplianceData: ComplianceDashboardData = {
  healthScore: {
    overall: 87,
    crew: 92,
    aircraft: 85,
    documentation: 82,
    authorization: 90,
  },
  
  alerts: [
    {
      id: 'alert-1',
      severity: 'warning',
      category: 'crew',
      title: 'Captain J. Smith approaching duty limit',
      description: 'Current duty time: 11.5 hours of 14 hour limit',
      actionRequired: 'Schedule rest period before next flight',
      dueDate: addHours(2.5),
    },
    {
      id: 'alert-2',
      severity: 'critical',
      category: 'aircraft',
      title: 'N425AV inspection due',
      description: '100-hour inspection due in 8.5 flight hours',
      actionRequired: 'Schedule maintenance before next long flight',
      dueDate: addDays(2),
    },
    {
      id: 'alert-3',
      severity: 'warning',
      category: 'documentation',
      title: 'Insurance certificate expiring',
      description: 'Hull & Liability insurance expires in 28 days',
      actionRequired: 'Contact broker for renewal',
      dueDate: addDays(28),
    },
    {
      id: 'alert-4',
      severity: 'info',
      category: 'authorization',
      title: 'Morocco overflight permit renewal',
      description: 'Annual permit expires in 45 days',
      actionRequired: 'Submit renewal application',
      dueDate: addDays(45),
    },
  ],
  
  expiringItems: {
    count30Days: 3,
    count60Days: 7,
    count90Days: 12,
  },
  
  lastUpdated: new Date().toISOString(),
  
  countryAuthorizations: [
    {
      id: 'auth-us',
      country: 'United States',
      countryCode: 'US',
      regulationType: 'FAA Part 135',
      status: 'compliant',
      expiryDate: addDays(425),
      limitations: [
        'VFR operations authorized',
        'IFR operations authorized',
        'Maximum 30 passenger seats',
      ],
      documents: [
        {
          id: 'doc-us-1',
          name: 'Part 135 Certificate',
          type: 'Operating Certificate',
          uploadDate: addDays(-365),
          expiryDate: addDays(425),
          status: 'compliant',
        },
        {
          id: 'doc-us-2',
          name: 'Operations Specifications',
          type: 'OpSpecs',
          uploadDate: addDays(-90),
          expiryDate: null,
          status: 'compliant',
        },
      ],
      region: 'Americas',
    },
    {
      id: 'auth-uk',
      country: 'United Kingdom',
      countryCode: 'GB',
      regulationType: 'UK CAA Commercial',
      status: 'compliant',
      expiryDate: addDays(180),
      limitations: [
        'Commercial air transport operations',
        'EASA Part-NCO compliant',
      ],
      documents: [
        {
          id: 'doc-uk-1',
          name: 'AOC Certificate',
          type: 'Operating Certificate',
          uploadDate: addDays(-185),
          expiryDate: addDays(180),
          status: 'compliant',
        },
      ],
      region: 'Europe',
    },
    {
      id: 'auth-fr',
      country: 'France',
      countryCode: 'FR',
      regulationType: 'EASA OPS',
      status: 'expiring',
      expiryDate: addDays(25),
      limitations: [
        'Commercial operations',
        'Business aviation',
      ],
      documents: [
        {
          id: 'doc-fr-1',
          name: 'EASA AOC',
          type: 'Operating Certificate',
          uploadDate: addDays(-340),
          expiryDate: addDays(25),
          status: 'expiring',
        },
      ],
      region: 'Europe',
    },
    {
      id: 'auth-ae',
      country: 'United Arab Emirates',
      countryCode: 'AE',
      regulationType: 'GCAA Permit',
      status: 'compliant',
      expiryDate: addDays(156),
      limitations: [
        'Dubai Int\'l Airport approved',
        'Al Maktoum Int\'l approved',
      ],
      documents: [
        {
          id: 'doc-ae-1',
          name: 'Landing Permit',
          type: 'International Permit',
          uploadDate: addDays(-209),
          expiryDate: addDays(156),
          status: 'compliant',
        },
      ],
      region: 'Middle East',
    },
    {
      id: 'auth-ma',
      country: 'Morocco',
      countryCode: 'MA',
      regulationType: 'Overflight Permit',
      status: 'expiring',
      expiryDate: addDays(45),
      limitations: [
        'Overflight only',
        'No landing rights',
      ],
      documents: [
        {
          id: 'doc-ma-1',
          name: 'Annual Overflight Permit',
          type: 'Overflight Authorization',
          uploadDate: addDays(-320),
          expiryDate: addDays(45),
          status: 'expiring',
        },
      ],
      region: 'Africa',
    },
  ],
  
  crewDutyStatus: [
    {
      crewId: 'crew-001',
      name: 'Captain James Smith',
      role: 'PIC',
      currentDutyHours: 11.5,
      maxDutyHours: 14,
      restRequired: false,
      restUntil: null,
      upcomingFlights: ['AVN-881', 'AVN-882'],
      license: {
        type: 'ATP',
        number: 'ATP-123456789',
        expiryDate: addDays(720),
        issueDate: addDays(-1800),
        issuingAuthority: 'FAA',
      },
      medical: {
        class: 'First Class',
        expiryDate: addDays(180),
        restrictions: [],
      },
      typeRatings: [
        {
          aircraftType: 'Gulfstream G650',
          expiryDate: addDays(210),
          lastCheck: addDays(-155),
        },
        {
          aircraftType: 'Cessna Citation X',
          expiryDate: addDays(95),
          lastCheck: addDays(-270),
        },
      ],
      dutyHistory: [
        { date: addDays(-1), hours: 6.5, flightId: 'AVN-880' },
        { date: addDays(-2), hours: 5.0, flightId: 'AVN-879' },
        { date: addDays(-4), hours: 7.5, flightId: 'AVN-878' },
      ],
    },
    {
      crewId: 'crew-002',
      name: 'First Officer Sarah Johnson',
      role: 'SIC',
      currentDutyHours: 3.2,
      maxDutyHours: 14,
      restRequired: false,
      restUntil: null,
      upcomingFlights: ['AVN-883'],
      license: {
        type: 'Commercial Pilot',
        number: 'CPL-987654321',
        expiryDate: addDays(540),
        issueDate: addDays(-1200),
        issuingAuthority: 'FAA',
      },
      medical: {
        class: 'First Class',
        expiryDate: addDays(165),
        restrictions: ['Corrective Lenses Required'],
      },
      typeRatings: [
        {
          aircraftType: 'Bombardier Global 6000',
          expiryDate: addDays(275),
          lastCheck: addDays(-90),
        },
      ],
      dutyHistory: [
        { date: addDays(-1), hours: 3.2, flightId: 'AVN-880' },
        { date: addDays(-3), hours: 4.8, flightId: 'AVN-877' },
      ],
    },
    {
      crewId: 'crew-003',
      name: 'Captain Michael Chen',
      role: 'PIC',
      currentDutyHours: 0,
      maxDutyHours: 14,
      restRequired: true,
      restUntil: addHours(8),
      upcomingFlights: [],
      license: {
        type: 'ATP',
        number: 'ATP-555123456',
        expiryDate: addDays(890),
        issueDate: addDays(-1500),
        issuingAuthority: 'FAA',
      },
      medical: {
        class: 'First Class',
        expiryDate: addDays(145),
        restrictions: [],
      },
      typeRatings: [
        {
          aircraftType: 'Dassault Falcon 7X',
          expiryDate: addDays(320),
          lastCheck: addDays(-45),
        },
      ],
      dutyHistory: [
        { date: addDays(-1), hours: 9.5, flightId: 'AVN-876' },
        { date: addDays(-2), hours: 8.0, flightId: 'AVN-875' },
      ],
    },
    {
      crewId: 'crew-004',
      name: 'Flight Attendant Emily Roberts',
      role: 'FA',
      currentDutyHours: 6.0,
      maxDutyHours: 14,
      restRequired: false,
      restUntil: null,
      upcomingFlights: ['AVN-881'],
      license: {
        type: 'Flight Attendant Certificate',
        number: 'FA-789456123',
        expiryDate: addDays(420),
        issueDate: addDays(-945),
        issuingAuthority: 'FAA',
      },
      medical: {
        class: 'Basic Medical',
        expiryDate: addDays(280),
        restrictions: [],
      },
      typeRatings: [],
      dutyHistory: [
        { date: addDays(-1), hours: 6.0, flightId: 'AVN-880' },
        { date: addDays(-3), hours: 5.5, flightId: 'AVN-879' },
      ],
    },
  ],
  
  operatorCompliance: {
    id: 'op-001',
    operatorName: 'Avion Charter Services',
    aocNumber: 'AOC-US-12345',
    certificates: [
      {
        id: 'cert-aoc',
        name: 'Air Operator Certificate',
        type: 'AOC',
        status: 'compliant',
        issueDate: addDays(-730),
        expiryDate: addDays(365),
        issuingAuthority: 'FAA',
        scope: 'Part 135 charter operations',
      },
      {
        id: 'cert-hull',
        name: 'Hull Insurance',
        type: 'Insurance',
        status: 'expiring',
        issueDate: addDays(-337),
        expiryDate: addDays(28),
        issuingAuthority: 'Global Aviation Insurance Ltd',
      },
      {
        id: 'cert-liability',
        name: 'Liability Insurance',
        type: 'Insurance',
        status: 'expiring',
        issueDate: addDays(-337),
        expiryDate: addDays(28),
        issuingAuthority: 'Global Aviation Insurance Ltd',
      },
      {
        id: 'cert-pax',
        name: 'Passenger Liability',
        type: 'Insurance',
        status: 'expiring',
        issueDate: addDays(-337),
        expiryDate: addDays(28),
        issuingAuthority: 'Global Aviation Insurance Ltd',
      },
    ],
    approvedAirports: ['KJFK', 'KLAX', 'EGLL', 'LFPG', 'OMDB', 'CYYZ'],
    approvedRoutes: [
      'US Domestic',
      'Transatlantic',
      'Caribbean',
      'Central America',
    ],
    auditHistory: [
      {
        id: 'audit-001',
        date: addDays(-45),
        type: 'FAA Surveillance',
        findings: 2,
        status: 'passed',
      },
      {
        id: 'audit-002',
        date: addDays(-180),
        type: 'Internal Safety Audit',
        findings: 5,
        status: 'passed',
      },
      {
        id: 'audit-003',
        date: addDays(-365),
        type: 'FAA Certification',
        findings: 0,
        status: 'passed',
      },
    ],
  },
  
  aircraftCompliance: [
    {
      id: 'ac-001',
      tailNumber: 'N425AV',
      registrationCountry: 'United States',
      aircraftType: 'Gulfstream G650',
      airworthyStatus: 'due_soon',
      nextInspectionDate: addDays(2),
      hoursUntilInspection: 8.5,
      openDiscrepancies: 1,
      certifications: ['RVSM', 'ETOPS', 'CAT II'],
      maintenanceStatus: [
        {
          type: 'Airframe Hours',
          current: 4891.5,
          limit: 5000,
          unit: 'hours',
          dueDate: addDays(2),
          status: 'due_soon',
        },
        {
          type: 'Engine 1 Cycles',
          current: 3245,
          limit: 3500,
          unit: 'cycles',
          dueDate: addDays(45),
          status: 'current',
        },
        {
          type: 'Engine 2 Cycles',
          current: 3198,
          limit: 3500,
          unit: 'cycles',
          dueDate: addDays(52),
          status: 'current',
        },
      ],
      certificateOfAirworthiness: {
        id: 'coa-001',
        name: 'Certificate of Airworthiness',
        type: 'C of A',
        uploadDate: addDays(-730),
        expiryDate: addDays(365),
        status: 'compliant',
      },
      registrationDocument: {
        id: 'reg-001',
        name: 'Aircraft Registration',
        type: 'Registration',
        uploadDate: addDays(-1825),
        expiryDate: null,
        status: 'compliant',
      },
      insuranceCertificate: {
        id: 'ins-001',
        name: 'Aircraft Insurance',
        type: 'Insurance',
        uploadDate: addDays(-337),
        expiryDate: addDays(28),
        status: 'expiring',
      },
    },
    {
      id: 'ac-002',
      tailNumber: 'N787FL',
      registrationCountry: 'United States',
      aircraftType: 'Bombardier Global 6000',
      airworthyStatus: 'current',
      nextInspectionDate: addDays(89),
      hoursUntilInspection: 125,
      openDiscrepancies: 0,
      certifications: ['RVSM', 'CAT III'],
      maintenanceStatus: [
        {
          type: 'Airframe Hours',
          current: 2875,
          limit: 3000,
          unit: 'hours',
          dueDate: addDays(89),
          status: 'current',
        },
        {
          type: 'Engine 1 Cycles',
          current: 1890,
          limit: 2500,
          unit: 'cycles',
          dueDate: addDays(145),
          status: 'current',
        },
        {
          type: 'Engine 2 Cycles',
          current: 1905,
          limit: 2500,
          unit: 'cycles',
          dueDate: addDays(142),
          status: 'current',
        },
      ],
      certificateOfAirworthiness: {
        id: 'coa-002',
        name: 'Certificate of Airworthiness',
        type: 'C of A',
        uploadDate: addDays(-548),
        expiryDate: addDays(547),
        status: 'compliant',
      },
      registrationDocument: {
        id: 'reg-002',
        name: 'Aircraft Registration',
        type: 'Registration',
        uploadDate: addDays(-1460),
        expiryDate: null,
        status: 'compliant',
      },
      insuranceCertificate: {
        id: 'ins-002',
        name: 'Aircraft Insurance',
        type: 'Insurance',
        uploadDate: addDays(-337),
        expiryDate: addDays(28),
        status: 'expiring',
      },
    },
    {
      id: 'ac-003',
      tailNumber: 'N350JT',
      registrationCountry: 'United States',
      aircraftType: 'Cessna Citation X',
      airworthyStatus: 'current',
      nextInspectionDate: addDays(123),
      hoursUntilInspection: 198,
      openDiscrepancies: 0,
      certifications: ['RVSM'],
      maintenanceStatus: [
        {
          type: 'Airframe Hours',
          current: 5802,
          limit: 6000,
          unit: 'hours',
          dueDate: addDays(123),
          status: 'current',
        },
        {
          type: 'Engine 1 Cycles',
          current: 4120,
          limit: 4500,
          unit: 'cycles',
          dueDate: addDays(156),
          status: 'current',
        },
        {
          type: 'Engine 2 Cycles',
          current: 4098,
          limit: 4500,
          unit: 'cycles',
          dueDate: addDays(162),
          status: 'current',
        },
      ],
      certificateOfAirworthiness: {
        id: 'coa-003',
        name: 'Certificate of Airworthiness',
        type: 'C of A',
        uploadDate: addDays(-425),
        expiryDate: addDays(670),
        status: 'compliant',
      },
      registrationDocument: {
        id: 'reg-003',
        name: 'Aircraft Registration',
        type: 'Registration',
        uploadDate: addDays(-2190),
        expiryDate: null,
        status: 'compliant',
      },
      insuranceCertificate: {
        id: 'ins-003',
        name: 'Aircraft Insurance',
        type: 'Insurance',
        uploadDate: addDays(-337),
        expiryDate: addDays(28),
        status: 'expiring',
      },
    },
  ],
};
